# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08571d170939680c7713c190be819953366283b06f6a277ae2ea3e24357565d4a7fb61baded556c941f274a971d8553accc3e0b8941886473eb13107a6a43c4b

test:
  secret_key_base: da15bdc36c2e34bf6098c76093e30e5844a96715b18cc134b2689abf6c8408a67dcceffc2c341af04e69405bb032fb330f9c846c63edc1a0561a1778bae5203f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
